# Generated by Django 3.2.7 on 2021-09-21 16:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('remote_pubkey', models.CharField(max_length=66)),
                ('chan_id', models.IntegerField(primary_key=True, serialize=False)),
                ('funding_txid', models.CharField(max_length=64)),
                ('output_index', models.IntegerField()),
                ('capacity', models.BigIntegerField()),
                ('local_balance', models.BigIntegerField()),
                ('remote_balance', models.BigIntegerField()),
                ('unsettled_balance', models.BigIntegerField()),
                ('initiator', models.BooleanField()),
                ('alias', models.CharField(max_length=32)),
                ('base_fee', models.IntegerField()),
                ('fee_rate', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('is_open', models.BooleanField()),
                ('auto_rebalance', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Forwards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forward_date', models.DateTimeField()),
                ('chan_id_in', models.IntegerField()),
                ('chan_id_out', models.IntegerField()),
                ('chan_in_alias', models.CharField(default='Unknown', max_length=32)),
                ('chan_out_alias', models.CharField(default='Unknown', max_length=32)),
                ('amt_in_msat', models.BigIntegerField()),
                ('amt_out_msat', models.BigIntegerField()),
                ('fee', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('creation_date', models.DateTimeField()),
                ('settle_date', models.DateTimeField()),
                ('r_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('amt_paid', models.BigIntegerField()),
                ('state', models.IntegerField()),
                ('chan_in', models.IntegerField(null=True)),
                ('chan_in_alias', models.CharField(max_length=32, null=True)),
                ('keysend_preimage', models.CharField(max_length=64, null=True)),
                ('message', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocalSettings',
            fields=[
                ('key', models.CharField(default=None, max_length=20, primary_key=True, serialize=False)),
                ('value', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('creation_date', models.DateTimeField()),
                ('payment_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('fee', models.FloatField()),
                ('status', models.IntegerField()),
                ('index', models.IntegerField()),
                ('chan_out', models.IntegerField(null=True)),
                ('chan_out_alias', models.CharField(max_length=32, null=True)),
                ('keysend_preimage', models.CharField(max_length=64, null=True)),
                ('message', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Peers',
            fields=[
                ('pubkey', models.CharField(max_length=66, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('sat_sent', models.BigIntegerField()),
                ('sat_recv', models.BigIntegerField()),
                ('inbound', models.BooleanField()),
                ('connected', models.BooleanField()),
                ('last_reconnected', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rebalancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested', models.DateTimeField(default=django.utils.timezone.now)),
                ('value', models.IntegerField()),
                ('fee_limit', models.IntegerField()),
                ('outgoing_chan_ids', models.TextField(default='[]')),
                ('last_hop_pubkey', models.CharField(default='', max_length=66)),
                ('duration', models.IntegerField()),
                ('start', models.DateTimeField(null=True)),
                ('stop', models.DateTimeField(null=True)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_id', models.IntegerField()),
                ('step', models.IntegerField()),
                ('chan_id', models.IntegerField()),
                ('alias', models.CharField(max_length=32)),
                ('chan_capacity', models.BigIntegerField()),
                ('node_pubkey', models.CharField(max_length=66)),
                ('amt', models.FloatField()),
                ('fee', models.FloatField()),
                ('payment_hash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.payments')),
            ],
            options={
                'unique_together': {('payment_hash', 'attempt_id', 'step')},
            },
        ),
    ]
