# Generated by Django 3.2.7 on 2021-09-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forwards',
            name='chan_in_alias',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='forwards',
            name='chan_out_alias',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
