# Generated by Django 3.2.7 on 2021-09-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0003_auto_20210927_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='channels',
            name='local_commit',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
