# Generated by Django 3.2.7 on 2021-10-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0006_auto_20210928_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='message',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='message',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
