# Generated by Django 3.2.7 on 2021-10-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0007_auto_20211002_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='channels',
            name='ar_target',
            field=models.IntegerField(default=100),
        ),
    ]
