# Generated by Django 3.2.7 on 2021-10-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0008_channels_ar_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='Onchain',
            fields=[
                ('tx_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField()),
                ('block_hash', models.CharField(max_length=64)),
                ('block_height', models.IntegerField()),
                ('time_stamp', models.DateTimeField()),
                ('fee', models.IntegerField()),
                ('label', models.CharField(max_length=100)),
            ],
        ),
    ]
