# Generated by Django 3.2.7 on 2021-10-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0009_onchain'),
    ]

    operations = [
        migrations.AddField(
            model_name='rebalancer',
            name='payment_hash',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
    ]
