# Generated by Django 3.2.7 on 2021-10-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0011_pendinghtlcs'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinghtlcs',
            name='chan_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendinghtlcs',
            name='forwarding_alias',
            field=models.CharField(default='---', max_length=32),
            preserve_default=False,
        ),
    ]
