# Generated by Django 3.2.7 on 2021-11-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0012_auto_20211018_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='rebalancer',
            name='target_alias',
            field=models.CharField(default='', max_length=32),
        ),
    ]
