# Generated by Django 3.2.7 on 2021-12-18 22:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0013_rebalancer_target_alias'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedHTLCs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.IntegerField()),
                ('chan_id_in', models.IntegerField()),
                ('chan_id_out', models.IntegerField()),
                ('chan_in_alias', models.CharField(max_length=32, null=True)),
                ('chan_out_alias', models.CharField(max_length=32, null=True)),
                ('wire_failure', models.IntegerField()),
                ('failure_detail', models.IntegerField()),
                ('missed_fee', models.FloatField()),
            ],
        ),
    ]
