# Generated by Django 3.2.7 on 2021-12-26 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0014_failedhtlcs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoices',
        ),
    ]
