# Generated by Django 3.2.7 on 2021-12-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0015_delete_invoices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('creation_date', models.DateTimeField()),
                ('settle_date', models.DateTimeField(default=None, null=True)),
                ('r_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('amt_paid', models.BigIntegerField()),
                ('state', models.IntegerField()),
                ('chan_in', models.IntegerField(null=True)),
                ('chan_in_alias', models.CharField(max_length=32, null=True)),
                ('keysend_preimage', models.CharField(max_length=64, null=True)),
                ('message', models.CharField(max_length=255, null=True)),
                ('index', models.IntegerField()),
            ],
        ),
    ]
