# Generated by Django 3.2.7 on 2022-01-06 20:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0016_auto_20220106_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autopilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('chan_id', models.IntegerField()),
                ('peer_alias', models.CharField(max_length=32)),
                ('setting', models.CharField(max_length=20)),
                ('old_value', models.IntegerField()),
                ('new_value', models.IntegerField()),
            ],
        ),
    ]
