# Generated by Django 3.2.7 on 2022-01-14 22:18

from django.db import migrations, models
from django.db.models import F, IntegerField
from django.db.models.functions import Round

def update_defaults(apps, schedma_editor):
    channels = apps.get_model('gui', 'channels')
    settings = apps.get_model('gui', 'localsettings')
    try:
        if settings.objects.filter(key='AR-Target%').exists():
            ar_amt_target = float(settings.objects.filter(key='AR-Target%')[0].value)
        else:
            ar_amt_target = 0.05
        channels.objects.all().update(ar_amt_target=Round(F('capacity')*ar_amt_target, output_field=IntegerField()))
    except Exception as e:
        print('Migration step failed:', str(e))
    try:
        if settings.objects.filter(key='AR-Outbound%').exists():
            ar_out_target = float(settings.objects.filter(key='AR-Outbound%')[0].value)
        else:
            ar_out_target = 0.75
        channels.objects.all().update(ar_out_target=ar_out_target*100)
    except Exception as e:
        print('Migration step failed:', str(e))

def revert_defaults(apps, schedma_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0017_autopilot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channels',
            old_name='ar_target',
            new_name='ar_in_target',
        ),
        migrations.AddField(
            model_name='channels',
            name='ar_amt_target',
            field=models.BigIntegerField(default=100000),
        ),
        migrations.AddField(
            model_name='channels',
            name='ar_out_target',
            field=models.IntegerField(default=75),
        ),
        migrations.RunPython(update_defaults, revert_defaults),
    ]
