# Generated by Django 3.2.7 on 2022-01-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0017_autopilot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channels',
            old_name='ar_target',
            new_name='ar_in_target',
        ),
        migrations.AddField(
            model_name='channels',
            name='ar_amt_target',
            field=models.BigIntegerField(default=100000),
        ),
        migrations.AddField(
            model_name='channels',
            name='ar_out_target',
            field=models.IntegerField(default=75),
        ),
    ]
