# Generated by Django 3.2.7 on 2022-01-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0018_auto_20220114_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channels',
            name='ar_amt_target',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='channels',
            name='ar_out_target',
            field=models.IntegerField(),
        ),
    ]
