# Generated by Django 3.2.7 on 2022-01-26 21:13

from django.db import migrations, models
import django.utils.timezone

def update_defaults(apps, schedma_editor):
    channels = apps.get_model('gui', 'channels')
    settings = apps.get_model('gui', 'localsettings')
    try:
        if settings.objects.filter(key='AR-MaxCost%').exists():
            ar_max_cost = float(settings.objects.filter(key='AR-MaxCost%')[0].value)
        else:
            ar_max_cost = 0.75
        channels.objects.all().update(ar_max_cost=ar_max_cost*100)
    except Exception as e:
        print('Migration step failed:', str(e))

def revert_defaults(apps, schedma_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0019_auto_20220122_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='channels',
            name='ar_max_cost',
            field=models.IntegerField(default=65),
        ),
        migrations.AddField(
            model_name='channels',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='channels',
            name='local_disabled',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channels',
            name='remote_disabled',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payments',
            name='cleaned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='message',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.RunPython(update_defaults, revert_defaults),
        migrations.AlterField(
            model_name='channels',
            name='ar_max_cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='channels',
            name='last_update',
            field=models.DateTimeField(),
        ),
    ]
