# Generated by Django 3.2.7 on 2022-04-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0025_alter_closures_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='channels',
            name='local_cltv',
            field=models.IntegerField(default=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channels',
            name='remote_cltv',
            field=models.IntegerField(default=40),
            preserve_default=False,
        ),
    ]
