# Generated by Django 3.2.7 on 2022-05-06 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0026_auto_20220420_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='rebalancer',
            name='manual',
            field=models.BooleanField(default=False),
        ),
    ]
