# Generated by Django 3.2.7 on 2022-06-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0027_rebalancer_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinghtlcs',
            name='forwarding_channel',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='rebalancer',
            name='fee_limit',
            field=models.FloatField(),
        ),
    ]
