# Generated by Django 3.2.7 on 2022-06-27 08:47
from django.db import migrations

def update_percent_vars(apps, schedma_editor):
    settings = apps.get_model('gui', 'localsettings')
    try:
        if settings.objects.filter(key='AR-MaxCost%').exists():
            current_value = settings.objects.filter(key='AR-MaxCost%')[0]
            current_value.value = int(float(current_value.value)*100)
            current_value.save()
        if settings.objects.filter(key='AR-Outbound%').exists():
            current_value = settings.objects.filter(key='AR-Outbound%')[0]
            current_value.value = int(float(current_value.value)*100)
            current_value.save()
        if settings.objects.filter(key='AR-Target%').exists():
            current_value = settings.objects.filter(key='AR-Target%')[0]
            current_value.value = int(float(current_value.value)*100)
            current_value.save()
    except Exception as e:
        print('Migration step failed:', str(e))

def revert_percent_vars(apps, schedma_editor):
    settings = apps.get_model('gui', 'localsettings')
    try:
        if settings.objects.filter(key='AR-MaxCost%').exists():
            current_value = settings.objects.filter(key='AR-MaxCost%')[0]
            current_value.value = int(current_value.value)/100
            current_value.save()
        if settings.objects.filter(key='AR-Outbound%').exists():
            current_value = settings.objects.filter(key='AR-Outbound%')[0]
            current_value.value = int(current_value.value)/100
            current_value.save()
        if settings.objects.filter(key='AR-Target%').exists():
            current_value = settings.objects.filter(key='AR-Target%')[0]
            current_value.value = int(current_value.value)/100
            current_value.save()
    except Exception as e:
        print('Migration reversion step failed:', str(e))

class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0028_auto_20220620_1105'),
    ]

    operations = [
        migrations.RunPython(update_percent_vars, revert_percent_vars),
    ]
