# Generated by Django 3.2.7 on 2022-07-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0029_update_percent_vars'),
    ]

    operations = [
        migrations.AddField(
            model_name='channels',
            name='closing_costs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rebalancer',
            name='fees_paid',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='channels',
            name='ar_in_target',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='channels',
            name='auto_fees',
            field=models.BooleanField(),
        ),
    ]
