# Generated by Django 3.2.7 on 2022-08-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0030_auto_20220722_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingChannels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funding_txid', models.CharField(max_length=64)),
                ('output_index', models.IntegerField()),
                ('local_base_fee', models.IntegerField(default=None, null=True)),
                ('local_fee_rate', models.IntegerField(default=None, null=True)),
                ('local_cltv', models.IntegerField(default=None, null=True)),
                ('auto_rebalance', models.BooleanField(default=None, null=True)),
                ('ar_amt_target', models.BigIntegerField(default=None, null=True)),
                ('ar_in_target', models.IntegerField(default=None, null=True)),
                ('ar_out_target', models.IntegerField(default=None, null=True)),
                ('ar_max_cost', models.IntegerField(default=None, null=True)),
                ('auto_fees', models.BooleanField(default=None, null=True)),
            ],
            options={
                'unique_together': {('funding_txid', 'output_index')},
            },
        ),
    ]
