# Generated by Django 3.2.7 on 2022-09-27 01:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0032_auto_20220913_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvoidNodes',
            fields=[
                ('pubkey', models.CharField(max_length=66, primary_key=True, serialize=False)),
                ('notes', models.CharField(max_length=1000, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='channels',
            name='local_max_htlc_msat',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channels',
            name='local_min_htlc_msat',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channels',
            name='remote_max_htlc_msat',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channels',
            name='remote_min_htlc_msat',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoices',
            name='is_revenue',
            field=models.BooleanField(default=False),
        ),
    ]
