# Generated by Django 3.2.7 on 2022-12-20 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0033_auto_20220926_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeerEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('chan_id', models.CharField(max_length=20)),
                ('peer_alias', models.CharField(max_length=32)),
                ('event', models.CharField(max_length=20)),
                ('old_value', models.BigIntegerField()),
                ('new_value', models.BigIntegerField()),
            ],
        ),
    ]
