# Generated by Django 3.2.7 on 2023-03-03 01:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0034_peerevents'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistFailedHTLC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('chan_id_in', models.CharField(max_length=20)),
                ('chan_id_out', models.CharField(max_length=20)),
                ('chan_in_alias', models.CharField(max_length=32, null=True)),
                ('chan_out_alias', models.CharField(max_length=32, null=True)),
                ('htlc_count', models.IntegerField()),
                ('amount_sum', models.BigIntegerField()),
                ('fee_sum', models.BigIntegerField()),
                ('liq_avg', models.BigIntegerField()),
                ('pending_avg', models.BigIntegerField()),
                ('balance_count', models.IntegerField()),
                ('downstream_count', models.IntegerField()),
                ('other_count', models.IntegerField()),
            ],
            options={
                'unique_together': {('date', 'chan_id_in', 'chan_id_out')},
            },
        ),
    ]
