# Generated by Django 4.1.5 on 2023-03-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0035_histfailedhtlc'),
    ]

    operations = [
        migrations.AddField(
            model_name='channels',
            name='label',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
    ]
