# Generated by Django 4.1.5 on 2023-08-06 17:59

from django.db import migrations, models
import django.db.models.deletion

from gui.models import Groups, Channels, Settings

def migrate_update_channels(apps, schema_editor):
    channels = Channels.objects.all()
    lndg_default = Groups(name="", id=0) # default
    lndg_default.save()
    for ch in channels:
        lndg_default.channels.add(ch)
    lndg_default.save()

    print('\nInitializing default settings...')
    Settings(key='AF-MaxRate', value='2500',group=lndg_default).save()
    Settings(key='AF-MinRate', value='0',group=lndg_default).save()
    Settings(key='AF-Increment', value='5',group=lndg_default).save()
    Settings(key='AF-Multiplier', value='5',group=lndg_default).save()
    Settings(key='AF-FailedHTLCs', value='25',group=lndg_default).save()
    Settings(key='AF-UpdateHours', value='24',group=lndg_default).save()
    Settings(key='AF-LowLiqLimit', value='5',group=lndg_default).save()
    Settings(key='AF-ExcessLimit', value='95',group=lndg_default).save()
    Settings(key='AF-Enabled', value='0',group=lndg_default).save()
    Settings(key='GUI-GraphLinks', value='https://amboss.space',group=lndg_default).save()
    Settings(key='GUI-NetLinks', value='https://mempool.space',group=lndg_default).save()
    Settings(key='LND-CleanPayments', value='0',group=lndg_default).save()
    Settings(key='LND-RetentionDays', value='30',group=lndg_default).save()
    Settings(key='AR-Outbound%', value='75',group=lndg_default).save()
    Settings(key='AR-Inbound%', value='100',group=lndg_default).save()
    Settings(key='AR-Target%', value='5',group=lndg_default).save()
    Settings(key='AR-MaxCost%', value='65',group=lndg_default).save()
    Settings(key='AR-Enabled', value='0',group=lndg_default).save()
    Settings(key='AR-MaxFeeRate', value='100',group=lndg_default).save()
    Settings(key='AR-Variance', value='0',group=lndg_default).save()
    Settings(key='AR-WaitPeriod', value='30',group=lndg_default).save()
    Settings(key='AR-Time', value='5',group=lndg_default).save()
    Settings(key='AR-Autopilot', value='0',group=lndg_default).save()
    Settings(key='AR-APDays', value='7',group=lndg_default).save()
    Settings(key='AR-Workers', value='1',group=lndg_default).save()

    print('\nApplying custom settings if user has any...')
    for sett in apps.get_model('gui', 'localsettings').objects.all():
        setting = lndg_default.settings_set.get(key=sett.key)
        setting.value = sett.value
        setting.save()

class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0036_peers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('channels', models.ManyToManyField(related_name='groups_set', to='gui.channels')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=None, max_length=20)),
                ('value', models.CharField(default=None, max_length=50)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.groups')),
            ],
        ),
        migrations.RunPython(migrate_update_channels, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='LocalSettings',
        )
    ]
