# Generated by Django 4.1.5 on 2023-08-02 23:06

from django.db import migrations, models
import django.db.models.deletion

from gui.models import Groups, Channels, Settings, LocalSettings

def migrate_update_channels(apps, schema_editor):
    channels = Channels.objects.all()
    lndg_default = Groups(id=1, name="") # default
    lndg_default.save()
    for ch in channels:
        lndg_default.channels.add(ch)
    lndg_default.save()

    locSettings = LocalSettings.objects.all()
    for sett in locSettings:
        settings = Settings(key=sett.key, value=sett.value)
        settings.group = lndg_default
        settings.save()

def revert_update_channels():
    migrations.DeleteModel(
        name="Groups",
    )

class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0036_peers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('channels', models.ManyToManyField(related_name='channels_list', to='gui.channels')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=50)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.groups')),
            ],
        ),
        migrations.RunPython(migrate_update_channels, revert_update_channels),
    ]
