# Generated by Django 5.0.2 on 2025-03-02 15:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0038_channels_local_inbound_base_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundFeeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('chan_id', models.CharField(max_length=20)),
                ('peer_alias', models.CharField(max_length=32)),
                ('setting', models.CharField(max_length=20)),
                ('old_value', models.IntegerField()),
                ('new_value', models.IntegerField()),
            ],
        ),
    ]
